# map
HEIGHT_MAP = 30
WIDTH_MAP = 120


# room
HEIGHT_MIN_ROOM = 4
WIDTH_MIN_ROOM = 4
ROOM_INDENT = 2
DOOR_COLORS = ['Red', 'Green', 'Blue']


# player 
PLAYER_START_HEALTH = 21 #1 + 20
PLAYER_START_AGILITY = 10
PLAYER_START_STRENGTH = 3


# enemies
ENEMY_HEALTH_MIN = 4
ENEMY_HEALTH_MAX = 8

ENEMY_AGILITY_MIN = 2
ENEMY_AGILITY_MAX = 10

ENEMY_STRENGTH_MIN = 1
ENEMY_STRENGTH_MAX = 4

ENEMY_HOSTILITY_MIN = 2
ENEMY_HOSTILITY_MAX = 12

VAMPIRE_MAX_HEALTH_DAMAGING_PERCENT = 10
GHOST_UNSEE_PERCENT_CHANCE = 40
SNAKE_WIZARD_SLEEP_PERCENT_CHANCE = 40

# items
FOOD_LOW = 1
FOOD_MID = 3
FOOD_HIGH = 6

POTION_HEALTH = 10
POTION_STRENGTH = 2
POTION_AGILITY = 6

SCROLL_HEALTH = 5
SCROLL_STRENGTH = 1
SCROLL_AGILITY = 3

WEAPON_LOW = 1
WEAPON_MID = 2
WEAPON_HIGH = 4
WEAPON_MAX = 6